runtime: python39

handlers:
  # This configures Google App Engine to serve the files in the app's static directory.
  - url: /static
    static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto

env_variables:
  OPENAI_API_KEY: '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'
  AWS_ACCESS_KEY_ID: 'AKIARYL7VC4FBWND6VHG'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_DEFAULT_REGION: 'us-east-1'
